language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
dist: trusty
script: "npm test && sudo sh -c 'export PATH=\"'\"$(dirname $(which node)):$PATH\"'\" && npm run test:root '"
after_script:
  - sudo chown -R $(whoami):$(whoami) coverage*
  - lcov-result-merger 'coverage*/lcov.info' | ./node_modules/.bin/coveralls
notifications:
  email: false
  webhooks:
    - https://pumabot.strugee.net/hubot/travis-ci-events
