language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
dist: trusty
after_script: ./node_modules/.bin/coveralls < coverage/lcov.info
notifications:
  email: false
  webhooks:
    - https://pumabot.strugee.net/hubot/travis-ci-events
